name: iOS Build and Test

on: 
  pull_request:
    branches:
      - '**'
    paths-ignore:
      - 'README.md'
      - 'documentation/**'
      - '.github/workflows/**'
      - '!.github/workflows/buildandtest.yml'
concurrency:
  # Ensure only the latest build of this PR runs.
  group: ${{ github.ref_name }}
  #  Cancel any inflight builds when a duplicate is detected.
  cancel-in-progress: true

jobs:
  build:
    name: Build and Test
    runs-on: macOS-13
    env:
        scheme: ${{ 'ActionsDemo' }}
        platform: ${{ 'iOS Simulator' }}
        device: ${{ 'iPhone 15 Pro' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Determine File To Build
        run: |
          if [ "`ls -A | grep -i \\.xcworkspace\$`" ]; then filetype_parameter="workspace" && file_to_build="`ls -A | grep -i \\.xcworkspace\$`"; else filetype_parameter="project" && file_to_build="`ls -A | grep -i \\.xcodeproj\$`"; fi
          file_to_build=`echo $file_to_build | awk '{$1=$1;print}'`
          echo "TYPE=$filetype_parameter" >> $GITHUB_ENV
          echo "FILE_TO_BUILD=$file_to_build" >> $GITHUB_ENV 
      - name: Configure Xcode Version
        run: echo "DEVELOPER_DIR=/Applications/Xcode_15.0.app" >> $GITHUB_ENV
      - name: Install Development Certificate
        uses: nickwph/apple-build-certificate-action@v1
        with:
          certificate-base64: ${{ secrets.CERTIFICATE_BASE64 }}
          certificate-password: ${{ secrets.CERTIFICATE_PASSWORD }}
      - name: Install Provisioning Profiles 
        uses: dietdoctor/install-ios-provisioning-profile@latest
        with:
          profile-base64: ${{ secrets.PROVISIONING_PROFILE }}
      - name: Build
        run: |
          xcodebuild build-for-testing -scheme "$scheme" -"${{ env.TYPE }}" "${{ env.FILE_TO_BUILD }}" -destination "platform=$platform,name=$device"
      - name: Test
        run: |
          xcodebuild test-without-building -scheme "$scheme" -"${{ env.TYPE }}" "${{ env.FILE_TO_BUILD }}" -destination "platform=$platform,name=$device"
